[config]

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/colors.css'

[templates.syshud]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/sys64/hud/colors.css'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel.ini'
output_path = '~/.config/fuzzel/fuzzel.ini'

[templates.niri]
input_path = '~/.config/matugen/templates/niri-layout.kdl'
output_path = '~/.config/niri/layout.kdl'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/theme.conf'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.gtklock]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/gtklock/colors.css'

[templates.wlogout]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.json]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.config/matugen/colors.json'

[templates.wlogout-hibernate]
input_path = '~/.config/matugen/templates/assets/hibernate.svg'
output_path = '~/.config/wlogout/assets/hibernate.svg'

[templates.wlogout-lock]
input_path = '~/.config/matugen/templates/assets/lock.svg'
output_path = '~/.config/wlogout/assets/lock.svg'

[templates.wlogout-suspend]
input_path = '~/.config/matugen/templates/assets/suspend.svg'
output_path = '~/.config/wlogout/assets/suspend.svg'

[templates.wlogout-reboot]
input_path = '~/.config/matugen/templates/assets/reboot.svg'
output_path = '~/.config/wlogout/assets/reboot.svg'

[templates.wlogout-logout]
input_path = '~/.config/matugen/templates/assets/logout.svg'
output_path = '~/.config/wlogout/assets/logout.svg'

[templates.wlogout-shutdown]
input_path = '~/.config/matugen/templates/assets/shutdown.svg'
output_path = '~/.config/wlogout/assets/shutdown.svg'
