background            {{colors.surface.default.hex}}
foreground            {{colors.on_surface.default.hex}}

selection_background  {{colors.primary.default.hex}}
selection_foreground  {{colors.on_primary.default.hex}}

cursor                {{colors.on_surface.default.hex}}
cursor_text_color     {{colors.surface.default.hex}}
url_color             {{colors.primary.default.hex}}

# Base ANSI (normal)
color0  #1e1e2e   # black (soft)
color1  #f38ba8   # red
color2  #a6e3a1   # green
color3  #f9e2af   # yellow
color4  #89b4fa   # blue
color5  #cba6f7   # magenta
color6  #94e2d5   # cyan
color7  #cdd6f4   # white

# Bright ANSI
color8  #585b70
color9  #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #cba6f7
color14 #94e2d5
color15 #ffffff
